# Generated by Django 5.0.2 on 2024-06-30 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeekDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (1, "Sunday"),
                            (2, "Monday"),
                            (3, "Tuesday"),
                            (4, "Wednesday"),
                            (5, "Thursday"),
                            (6, "Friday"),
                            (7, "Saturday"),
                        ],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_class", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("facebook", models.CharField(blank=True, max_length=50, null=True)),
                ("img", models.ImageField(upload_to="uploads/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="StudentAccount",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualification",
                    models.IntegerField(
                        choices=[
                            (10, "SSC"),
                            (12, "HSC"),
                            (13, "B.Sc in CSE"),
                            (14, "B.Sc in EEE"),
                            (15, "BA"),
                            (16, "MA"),
                            (9, "Class 9"),
                            (11, "Class 11"),
                            (8, "Class 8"),
                        ]
                    ),
                ),
                ("starting_hour", models.TimeField()),
                ("ending_hour", models.TimeField()),
                ("total_hours", models.TimeField()),
                ("description", models.TextField()),
                ("youtube", models.CharField(blank=True, max_length=50, null=True)),
                ("facebook", models.CharField(blank=True, max_length=50, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=50, null=True)),
                ("twitter", models.CharField(blank=True, max_length=50, null=True)),
                ("img", models.ImageField(upload_to="uploads/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TeacherAccount",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("week_days_option", models.ManyToManyField(to="accounts.weekday")),
            ],
        ),
    ]
