# Generated by Django 5.0.2 on 2024-07-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_student_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weekday",
            old_name="day",
            new_name="name",
        ),
    ]
