# Generated by Django 5.0.2 on 2024-07-21 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_day_weekday_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="weekday",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
