# Generated by Django 5.0.2 on 2024-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_weekday_slug_alter_student_img_alter_teacher_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="img",
            field=models.CharField(default="#", max_length=200),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="img",
            field=models.CharField(default="#", max_length=200),
        ),
    ]
