# Generated by Django 5.1 on 2024-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_student_img_alter_teacher_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="img",
            field=models.ImageField(default="#", upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="img",
            field=models.ImageField(default="#", upload_to="uploads/"),
        ),
    ]
