# Generated by Django 5.0.2 on 2024-07-17 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("fees", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("subjects", models.ManyToManyField(to="accounts.subjects")),
                ("teachers", models.ManyToManyField(to="accounts.teacher")),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("⭐", "⭐"),
                            ("⭐⭐", "⭐⭐"),
                            ("⭐⭐⭐", "⭐⭐⭐"),
                            ("⭐⭐⭐⭐", "⭐⭐⭐⭐"),
                            ("⭐⭐⭐⭐⭐", "⭐⭐⭐⭐⭐"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tuition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                        ],
                        default=("Pending", "Pending"),
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Offline", "Offline"),
                            ("Batch", "Batch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("starting_hour", models.TimeField()),
                ("ending_hour", models.TimeField()),
                ("total_hours", models.TimeField()),
                ("description", models.TextField()),
                ("canceled", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tuition",
                        to="accounts.student",
                    ),
                ),
                ("subjects", models.ManyToManyField(to="accounts.subjects")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.teacher",
                    ),
                ),
            ],
        ),
    ]
