# Generated by Django 5.0.2 on 2024-07-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tuition", "0003_rename_reviewer_review_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="student",
            new_name="reviewer",
        ),
    ]
