# Generated by Django 5.0.2 on 2024-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tuition", "0007_alter_tuition_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tuition",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Ongoing", "Ongoing"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
