# Generated by Django 5.0.2 on 2024-07-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_weekday_slug_alter_student_img_alter_teacher_img"),
        ("tuition", "0008_alter_tuition_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuition",
            name="week_days_option",
            field=models.ManyToManyField(to="accounts.weekday"),
        ),
    ]
